-- Copyright (c) 2017, balping
-- https://github.com/balping 

-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.

-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.

-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.

CREATE TABLE "2013-01" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-02" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-03" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-04" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-05" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-06" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-07" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-08" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-09" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-10" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-11" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2013-12" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);

CREATE TABLE "2014-01" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-02" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-03" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-04" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-05" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-06" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-07" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-08" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-09" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-10" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-11" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2014-12" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);

CREATE TABLE "2015-01" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-02" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-03" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-04" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-05" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-06" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-07" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-08" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-09" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-10" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-11" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2015-12" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);

CREATE TABLE "2016-01" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-02" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-03" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-04" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-05" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-06" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-07" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-08" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-09" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-10" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-11" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2016-12" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);

CREATE TABLE "2017-01" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-02" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-03" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-04" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-05" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-06" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-07" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-08" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-09" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-10" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-11" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);
CREATE TABLE "2017-12" (
	"Event" TEXT,
	"Site (URL)" TEXT PRIMARY KEY,
	"White" TEXT,
	"Black" TEXT,
	"Result" TEXT,
	"Date (UTC)" TEXT,
	"Time (UTC)" TEXT,
	"White Elo" INTEGER,
	"Black Elo" INTEGER,
	"White Rating Change" TEXT,
	"Black Rating Change" TEXT,
	"ECO Code" TEXT,
	"Opening Name" TEXT,
	"Time Control" TEXT,
	"Termination" TEXT,
	"Game Length (Ply)" INTEGER,
	"Moves" TEXT);